sudo: required
language: csharp
solution: src/Chat.sln
services:
  - docker
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
script:
  - sudo apt-get install jq #install jq for json parsing
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region ap-southeast-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -t netcoreapps .
  - docker tag netcoreapps:latest $AWS_ECS_REPO_DOMAIN/netcoreapps
  - docker push $AWS_ECS_REPO_DOMAIN/netcoreapps:latest
  - aws ecs register-task-definition --cli-input-json file://task-definition.json --region ap-southeast-2
  - TASK_REVISION=$(aws ecs describe-task-definition --task-definition netcoreapps-chat-task --region ap-southeast-2 | jq '.taskDefinition.revision')
  - NEW_REVISION=$((TASK_REVISION + 1))
  - aws ecs update-service --cluster netcoreapps --service netcoreapps-chat-service --task-definition "netcoreapps-chat-task:$NEW_REVISION" --region ap-southeast-2
