language: csharp
os: linux
dist: xenial
sudo: required
mono: none
env: DOTNETCORE=1
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
  snaps:
  - name: dotnet-sdk
    classic: true
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version
  - chmod +x ./deploy-envs.sh
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi